In [26]:
import numpy as np
x=[1,2,3,4]
np.array(x)

array([1, 2, 3, 4])

In [27]:
y=np.array([4,5,8])
y.ndim  #to check dimension

1

In [21]:
type(y)

numpy.ndarray

In [22]:
l=[]
for i in range(1,5):
    int_1=int(input("enter values "))
    l.append(int_1)
np.array(l)    

array([2, 2, 3, 5])

In [28]:
# Dimensions in array
# 1-D Arrays: [1,2,3,4]
# 2-D Arrays: [[1,2,3,4]]
# 3-D Arrays: [[[1,2,3]]] -count from right there is 3 bracket and from left also there is 3 bracket . so it is 3rd dimensional array
# Higher Dimensional Arrays

# dim is used to check dimension

In [35]:
ar2=np.array([[1,2,3],[4,5,6]]) # same number of data hokheke chai 
# ar2=np.array([[1,2,3],[4,5,6,7,8]]) #error aai but old version me automatically list me convert kar di - 1 D
ar2

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
ar2.ndim

2

In [40]:
# 3 D
ar3=np.array([[[1,2,3],[1,4,5],[7,8,9]]])
ar3

array([[[1, 2, 3],
        [1, 4, 5],
        [7, 8, 9]]])

In [39]:
ar3.ndim

3

In [42]:
# n D array
ar_n=np.array([1,2,3],ndmin=10)
print(ar_n)

[[[[[[[[[[1 2 3]]]]]]]]]]


In [45]:
#Special NumPy Array
# Array filled with 0's
# Array filled with 1's
# Create an empty array
# An array with range of elements 
# Array diagonal element filled with 1's
# create an array with values that are spaced linearly in a specified interval

In [47]:
# Zero
ar_zero=np.zeros(4) # 1 D
ar_zero

array([0., 0., 0., 0.])

In [49]:
ar_zero1=np.zeros((3,4)) #2 D - 3 rows and 4 column
ar_zero1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])